version: '3.8'

networks:
  default:

services:
  db:
    image: mariadb
    container_name: conference
    ports:
    - 3306:3306
    volumes:
    - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: conference

      docker run -d -p 3306:3306 mariadb:10.5.8


